version: '3.9'

services:
  app:
    build: .
    env_file:
      - .env.local
    container_name: go-nosql-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge